document.addEventListener("DOMContentLoaded", function () {
    const langBtn = document.querySelector(".lang-btn");
    const langDropdown = document.querySelector(".lang-dropdown");
    const langOptions = document.querySelectorAll(".lang-dropdown a");

    // Til bo‘yicha tarjimalar
    const translations = {
        uz: {
            home1: "Bosh bo'lim",
            home2: "Biz haqimizda",
            home3: "Mahsulotlarimiz",
            home4: "Aloqa",
            home5: "Biz bilan bog'lanish",
            home6: "Olma",
            home7: "Banan",
            home8: "Anor",
            home9: "Kivi",
            home10: "Mango",
            home11: "Nok",
            home12: "Elektron pochtangizni kiriting",
            home13: "Telefon raqam",
            home14: "Fikringgizni biz bilan bo'lishing",
            home15: "Jo'natish",

            home16: "micco",
            home17: "Sharbat bilan boyitilgan MICCO ichimliklari",
            home18: "MICCO – Quvvat manbai!",
            home19: "Har bir tomchi Micco tanangizga kuch bag‘ishlab, kun davomida quvvat baxsh etadi.",
            home20: "Nok",
            home21: "Tabiiy Ta’m Manbai",
            home22: "Micco Ich, Tetiklan!",
            home23: "Har bir qultum Micco tanangizga energiya bag‘ishlab, kun davomida quvvat beradi.",
            home24: "Anor",
            home25: "Quvvat Va Tetiklik.",
            home26: "Micco Energiya Manbai",
            home27: "Sovuq Micco iching va uning ajoyib ta’mi bilan rohatlaning va tetiklaning.",
            home28: "Kivi",
            home29: "Har Qultumda Lazzat!",
            home30: "Micco Bilan Jonlan!",
            home31: "tetiklashtiruvchi",
            home32: "Mango",
            home33: "Sog‘lom Tanlov Micco!",
            home34: "Micco – Sof Ta’m",
            home35: "Micco ichimligi organizmni suv bilan to‘yintiradi va salomatligingizni qo‘llab-quvvatlaydi.",
            home36: "Banan",

            home37: "Anor",
            home38: "Biz haqimizda",
            home39: "Jonlantiruvchi Sof Ichimlik",
            home40: "Micco ichimligi tabiiy tarkibga ega bo‘lib, tanangizni tetiklantiradi, energiya beradi va sog‘lom hayot uchun yordam beradi.",
            home41: "Qaynoq holda quyiladi.",
            home42: "Mahsulot uchun belgilangan narx bozor narxida",
            home43: "Alkogolsiz, gazlanmagan tabiiy sharbat bilan boyitilgan",

            home44: "Tabiiy Tomchilar",
            home45: "Mahsulotlarimiz",
            home46: "Kivi",
            home47: "Micco <br> Alkogolsiz, gazlanmagan, pasteriziyatsilangan, tabiiy sharbat bilan boyitilgan «Micco» ichimligi.",
            home471: "Kirish",
            home48: "Anor",
            home49: "Micco<br>Alkogolsiz, gazlanmagan, pasteriziyatsilangan, tabiiy sharbat bilan boyitilgan «Micco» ichimligi.",
            home491: "Kirish",
            home50: "Olma",
            home51: "Micco<br>Alkogolsiz, gazlanmagan, pasteriziyatsilangan, tabiiy sharbat bilan boyitilgan «Micco» ichimligi.",
            home511: "Kirish",

            home52: "Qanday ishlaymiz",
            home53: "Micco milliy mahsulotimizning tayyorlanish jarayoni.",
            home54: "1-Bosqich <br>Yer osti tabiiy artesian suvlarini qazib olish.",
            home55: "Micco ichimligi 5 bosqichli filtrdan o‘tib, yuqori tozalik va xavfsizlikni ta’minlaydi.",
            home56: "Bosqichlar.",
            home57: "Chig'anoq filtri <br> Ko'mir filtri <br> Kartrij <br> Osmos membranasi <br> Ultrabinafsha filtri",
            home58: "2-Bosqich<br> Pasterizatsiya",
            home59: "Bu bosqichda filterlardan o'tgan tabiiy suv kerakli ingredientlar, aroma va tabiiy sharbat bilan boyitilib 93-95 daraja qaynatiladi.",
            home60: "3-Bosqich Qadoqlash",
            home61: "Tayyor bo'lgan mahsulot 0,5 va 1 litr hajmli plastik idishlarga qaynoq holatda quyiladi.",

            home62: "TETIKLIK",
            home621: "Micco tabiiy tarkibi bilan sizga energiya va tetiklik baxsh etadi. Har kuningizni kuch bilan boshlang.",
            home63: "TABIIY",
            home64: "Micco faqat tabiiy mevalardan tayyorlanadi. Sof tarkib va sun’iy qo‘shimchalarsiz ichimlik bilan tanangizni himoya qiling.",
            home65: "LAZZATLI",
            home66: "Har bir qultum Micco o‘ziga xos ta’mi bilan sizga yoqimli zavq bag‘ishlaydi. Uning sof lazzatidan bahramand bo‘ling.",
            home67: "TURFA XIL",
            home68: "Micco turli mevali ta’mlari bilan sizga har safar yangi lazzat baxsh etadi. O‘zingizga yoqqanini tanlang va rohatlaning.",

            home69: "Mijozlarimiz nima deyishadi",
            home70: "Izohlar",
            home71: "Micco ichimligini birinchi marta sinab ko‘rganimda uning tabiiy ta’mi va yoqimli tetiklantiruvchi xususiyatlari menga juda yoqdi. Endi har kuni ichaman!",
            home72: "Erkinova Soliha",
            home73: "Micco ichimligi energiya va tetiklik baxsh etadi. Ish kunim davomida charchamaslik uchun doimo yonimda bo‘ladi. Uning tabiiy ta’mi juda yoqimli!",
            home74: "Akbarov Jasur",
            home75: "Men sog‘lom turmush tarziga amal qilaman, shuning uchun faqat tabiiy ichimliklar ichaman. Micco tarkibida sun’iy qo‘shimchalar yo‘qligi meni juda quvontiradi!",
            home76: "Yuldosheva Malika",

            home77: "Aloqa",
            home78: "Biz bilan bog'lanish",
            home79: "Hamkorlik uchun",
            home80: "Hamkorligimiz orqali yangi imkoniyatlar ochiladi.",
            home81: "XABAR YUBORISH",

            home82: "Aloqa",
            home83: "Tel..",
            home84: "Email..",
            home85: "Manzil: Toshkent shahar Yangi Hayot tumani Yo'ldosh-10 mavzesi 63-A uy",
            home86: "Bo'limlar",
            home87: "Biz haqimizda",
            home88: "Mahsulotlarimiz",
            home89: "Mijozlar",
            home90: "Aloqa",
            home91: "Micco mahsulotlari",
            home92: "micco-Anor",
            home93: "micco-Olma",
            home94: "micco-Kivi",
            home95: "micco-Mango",
            home96: "Barcha huquqlar himoyalangan. Dizayn va ishlab chiqarish ",

            adash1: "Ba'tafsil",
            adash2: "Kirish",
            adash3: "Kirish",
            adash4: "Ismingiz",
            adash5: "izohingizni kiriting...",
        },
        en: {
            home1: "Home",
            home2: "About Us",
            home3: "Our Products",
            home4: "Contact",
            home5: "Contact us",
            home6: "Apple",
            home7: "Banana",
            home8: "Pomegranate",
            home9: "Kiwi",
            home10: "Mango",
            home11: "Pear",
            home12: "Enter your email",
            home13: "Phone number",
            home14: "Share your thoughts with us.",
            home15: "Send",

            home16: "micco",
            home17: "MICCO drinks enriched with juice",
            home18: "MICCO – Power source!",
            home19: "Every drop of Micco will energize your body and give you energy throughout the day.",
            home20: "Pear",
            home21: "Natural Flavor Source",
            home22: "Micco Drink, Trigger!",
            home23: "Every sip of Micco will energize your body and give you strength throughout the day.",
            home24: "Pomegranate",
            home25: "Power And Agility.",
            home26: "Micco Energy Source",
            home27: "Drink a cold Micco and enjoy its wonderful taste and refreshment.",
            home28: "Kiwi",
            home29: "Flavor in Every Sip!",
            home30: "Come Alive with Micco!",
            home31: "invigorating",
            home32: "Mango",
            home33: "Healthy Choice Micco!",
            home34: "Micco – Pure Taste",
            home35: "Mikko's drink saturates the body with water and increases your productivity.",
            home36: "Banana",

            home37: "Pomegranate",
            home38: "about Us",
            home39: "John gives them a clean drink",
            home40: "Micco drink has natural ingredients that refresh your body, give you energy, and support a healthy lifestyle.",
            home41: "It is poured while boiling.",
            home42: "The price set for the product is at the market price.",
            home43: "Alcohol-free, non-carbonated, enriched with natural juice",

            home44: "Natural drops",
            home45: "Our products",
            home46: "Kiwi",
            home47: "Micco <br> Non-alcoholic, non-carbonated, pasteurized, natural juice-enriched drink Micco.",
            home471: "Enter",
            home48: "Pomegranate",
            home49: "Micco<br>Non-alcoholic, non-carbonated, pasteurized, natural juice-enriched drink Micco.",
            home491: "Enter",
            home50: "Apple",
            home51: "Micco<br>Non-alcoholic, non-carbonated, pasteurized, natural juice-enriched drink Micco.",
            home511: "Enter",

            home52: "How we work",
            home53: "The process of making our national product Micco.",
            home54: "Stage 1 - Extraction of underground natural artesian water.",
            home55: "Micco drink passes through a 5-stage filter, ensuring high purity and safety.",
            home56: "Steps.",
            home57: "Shell filter <br> Carbon filter <br> Cartridge <br> Osmosis membrane <br> Ultraviolet filter",
            home58: "Stage 2<br> Pasteurization",
            home59: "At this stage, natural water that has passed through filters is enriched with the necessary ingredients, aromas, and natural juices and boiled to 93-95 degrees.",
            home60: "Stage 3: Packaging",
            home61: "The finished product is poured into 0.5 and 1 liter plastic containers while boiling.",

            home62: "FRESHNESS",
            home621: "Micco's natural ingredients give you energy and freshness. Start every day with energy.",
            home63: "NATURAL",
            home64: "Micco is made only from natural fruits. Protect your body with a drink with pure ingredients and no artificial additives.",
            home65: "DELICIOUS",
            home66: "Every sip of Micco will give you a pleasant pleasure with its unique taste. Enjoy its pure flavor.",
            home67: "TYPE OF SILVER",
            home68: "Micco offers a variety of fruity flavors to give you a new taste every time. Choose your favorite and enjoy.",

            home69: "What our customers say",
            home70: "Notes",
            home71: "When I first tried Micco, I loved its natural taste and pleasantly refreshing properties. Now I drink it every day!",
            home72: "Erkinova Soliha",
            home73: "Micco drink gives me energy and refreshment. It is always with me to keep me going during my working day. Its natural taste is very pleasant!",
            home74: "Akbarov Jasur",
            home75: "I follow a healthy lifestyle, so I only drink natural drinks. I am very happy that Micco does not contain artificial additives!",
            home76: "Yuldosheva Malika",

            home77: "Communication",
            home78: "contact us",
            home79: "For cooperation",
            home80: "New opportunities will open up through our collaboration.",
            home81: "SEND MESSAGE",

            home82: "Communication",
            home83: "Tel..",
            home84: "Email..",
            home85: "Address: 63-A, Yuldosh-10 area, Yangi Hayot district, Tashkent city",
            home86: "Departments",
            home87: "about Us",
            home88: "Our products",
            home89: "Customers",
            home90: "Communication",
            home91: "Micco products",
            home92: "micco-Pomegranate",
            home93: "micco-Apple",
            home94: "micco-Kiwi",
            home95: "micco-Mango",
            home96: "All rights reserved. Design and production",

            adash1: "In detail",
            adash2: "Enter",
            adash3: "Enter",
            adash4: "your name",
            adash5: "enter your comment...",
        },
        ru: {
            home1: "Главная",
            home2: "О нас",
            home3: "Наши продукты",
            home4: "Контакты",
            home5: "Связаться с нами",
            home6: "Яблоко",
            home7: "Банан",
            home8: "Гранат",
            home9: "Киви",
            home10: "Манго",
            home11: "Груша",
            home12: "Введите адрес электронной почты",
            home13: "Номер телефона",
            home14: "Поделитесь с нами своими мыслями.",
            home15: "Отправить",

            home16: "micco",
            home17: "Напитки MICCO, обогащенные соком",
            home18: "MICCO – Источник энергии!",
            home19: "Каждая капля Micco зарядит ваш организм энергией и даст вам заряд бодрости на весь день.",
            home20: "Груша",
            home21: "Натуральный источник ароматизатора",
            home22: "Микко Пей, Триггер!",
            home23: "Каждый глоток Micco зарядит ваш организм энергией и придаст сил на весь день.",
            home24: "Гранат",
            home25: "Сила и ловкость.",
            home26: "Источник энергии Микко",
            home27: "Выпейте холодный «Микко» и насладитесь его прекрасным вкусом и освежающим эффектом.",
            home28: "киви",
            home29: "Вкус в каждом глотке!",
            home30: "Оживайте вместе с Микко!",
            home31: "бодрящий",
            home32: "манго",
            home33: "Здоровый выбор, Микко!",
            home34: "Микко – Чистый Вкус",
            home35: "Напиток Микко насыщает организм водой и повышает вашу производительность.",
            home36: "Банан",

            home37: "Гранат",
            home38: "о нас",
            home39: "Джон дает им чистый напиток",
            home40: "В состав напитка Micco входят натуральные ингредиенты, которые освежают организм, придают энергию и поддерживают здоровый образ жизни.",
            home41: "Заливается во время кипения.",
            home42: "Цена на продукцию установлена ​​на уровне рыночной.",
            home43: "Безалкогольный, негазированный, обогащенный натуральным соком",

            home44: "Натуральные капли",
            home45: "Наши продукты",
            home46: "киви",
            home47: "Micco <br> Безалкогольный, негазированный, пастеризованный, натуральный сокосодержащий напиток «Микко».",
            home471: "Входить",
            home48: "Гранат",
            home49: "Микко<br>Безалкогольный, негазированный, пастеризованный, натуральный сокосодержащий напиток «Микко».",
            home491: "Входить",
            home50: "Яблоко",
            home51: "Микко<br>Безалкогольный, негазированный, пастеризованный, натуральный сокосодержащий напиток «Микко».",
            home511: "Входить",

            home52: "Как мы работаем",
            home53: "Процесс изготовления нашего национального продукта Микко.",
            home54: "1 этап - Добыча подземных природных артезианских вод.",
            home55: "Напиток Micco проходит через 5-ступенчатую фильтрацию, что обеспечивает высокую чистоту и безопасность.",
            home56: "Шаги.",
            home57: "Фильтр Shell <br> Угольный фильтр <br> Картридж <br> Мембрана осмоса <br> Ультрафиолетовый фильтр",
            home58: "Этап 2<br> Пастеризация",
            home59: "На этом этапе природная вода, прошедшая через фильтры, обогащается необходимыми компонентами, ароматами и натуральными соками и кипятится до 93-95 градусов.",
            home60: "Этап 3: Упаковка",
            home61: "Готовый продукт разливают в пластиковые емкости емкостью 0,5 и 1 л при кипячении.",

            home62: "СВЕЖЕСТЬ",
            home621: "Натуральные ингредиенты Micco дают вам энергию и свежесть. Начинайте каждый день с энергией.",
            home63: "ЕСТЕСТВЕННЫЙ",
            home64: "Micco производится только из натуральных фруктов. Защитите свой организм напитком из чистых ингредиентов и без искусственных добавок.",
            home65: "ВКУСНЫЙ",
            home66: "Каждый глоток Micco подарит вам приятное наслаждение своим неповторимым вкусом. Насладитесь его чистым вкусом.",
            home67: "ТИП СЕРЕБРА",
            home68: "Micco предлагает разнообразные фруктовые вкусы, чтобы каждый раз дарить вам новый вкус. Выбирайте свой любимый и наслаждайтесь.",

            home69: "Что говорят наши клиенты",
            home70: "Примечания",
            home71: "Когда я впервые попробовал Micco, мне очень понравился его натуральный вкус и приятные освежающие свойства. Теперь я пью его каждый день!",
            home72: "Эркинова Солиха",
            home73: "Напиток Micco дает мне энергию и свежесть. Он всегда со мной, чтобы поддерживать меня в течение рабочего дня. Его натуральный вкус очень приятен!",
            home74: "Акбаров Джасур",
            home75: "Я веду здоровый образ жизни, поэтому пью только натуральные напитки. Очень радует, что в Micco нет искусственных добавок!",
            home76: "Юлдошева Малика",

            home77: "Коммуникация",
            home78: "связаться с нами",
            home79: "Для сотрудничества",
            home80: "Благодаря нашему сотрудничеству откроются новые возможности.",
            home81: "ОТПРАВИТЬ СООБЩЕНИЕ",

            home82: "Коммуникация",
            home83: "Тел..",
            home84: "Email..",
            home85: "Адрес: город Ташкент, Янги Хаётский район, район Юлдош-10, 63-А",
            home86: "Отделы",
            home87: "о нас",
            home88: "Наши продукты",
            home89: "Клиенты",
            home90: "Коммуникация",
            home91: "Продукция Микко",
            home92: "микко-гранат",
            home93: "micco-Яблоко",
            home94: "микко-Киви",
            home95: "микко-Манго",
            home96: "Все права защищены. Дизайн и производство",

            adash1: "Подробно",
            adash2: "Входить",
            adash3: "Входить",
            adash4: "Ваше имя",
            adash5: "введите свой комментарий...",
        },
        kz: {
            home1: "Басты бөлім",
            home2: "Біз туралы",
            home3: "Өнімдеріміз",
            home4: "Байланыс",
            home5: "Бізбен хабарласыңыз",
            home6: "Алма",
            home7: "Банан",
            home8: "Анар",
            home9: "Киви",
            home10: "Манго",
            home11: "Алмұрт",
            home12: "Электрондық поштаңызды енгізіңіз",
            home13: "Телефон нөмірі",
            home14: "Бізбен өз ойларыңызбен бөлісіңіз.",
            home15: "Жіберу",

            home16: "micco",
            home17: "Шырынмен байытылған MICCO сусындары",
            home18: "MICCO – энергия көзі!",
            home19: "Micco-ның әрбір тамшысы денеңізді қуатпен толтырады және күні бойына қуат береді.",
            home20: "Алмұрт",
            home21: "Дәмнің табиғи көзі",
            home22: "Микко сусыны, триггер!",
            home23: "Micco-ның әрбір жұтымы денеңізді қуатпен толтырады және күні бойы күш береді.",
            home24: "Анар",
            home25: "Күш пен ептілік.",
            home26: "Микконың энергия көзі",
            home27: "Салқын Микко ішіп, оның керемет дәмі мен сергітетін әсерінен ләззат алыңыз.",
            home28: "киви",
            home29: "Әр жұтымнан дәм татыңыз!",
            home30: "Миккомен бірге тірі болыңыз!",
            home31: "қуаттандыратын",
            home32: "манго",
            home33: "Салауатты таңдау, Микко!",
            home34: "Микко – таза дәм",
            home35: "Микко сусыны денеңізді ылғалдандырады және өнімділікті арттырады.",
            home36: "Банан",

            home37: "Анар",
            home38: "біз туралы",
            home39: "Джон оларға мөлдір сусын береді",
            home40: "Micco сусынының құрамында денені сергітетін, қуат беретін және салауатты өмір салтын қолдайтын табиғи ингредиенттер бар.",
            home41: "Қайнаған кезде құйылады.",
            home42: "Өнімнің бағасы нарық деңгейінде белгіленеді.",
            home43: "Алкогольсіз, газдалмаған, табиғи шырынмен байытылған",

            home44: "Табиғи тамшылар",
            home45: "Біздің өнімдер",
            home46: "киви",
            home47: "Micco <br> «Микко» алкогольсіз, газдалмаған, пастерленген, табиғи шырын сусыны.",
            home471: "Енгізіңіз",
            home48: "Анар",
            home49: "Микко<br>Алкогольсіз, газдалмаған, пастерленген, табиғи шырыннан жасалған «Микко» сусыны.",
            home491: "Енгізіңіз",
            home50: "Алма",
            home51: "Микко<br>Алкогольсіз, газдалмаған, пастерленген, табиғи шырыннан жасалған «Микко» сусыны.",
            home511: "Енгізіңіз",

            home52: "Біз қалай жұмыс істейміз",
            home53: "Ұлттық өніміміз Микконың жасалу процесі.",
            home54: "1-кезең – жер асты табиғи артезиан суларын алу.",
            home55: "Micco сусыны 5 сатылы фильтрациядан өтеді, бұл жоғары тазалық пен қауіпсіздікті қамтамасыз етеді.",
            home56: "Қадамдар.",
            home57: "Қабық сүзгісі <br> Көміртекті фильтр <br> Картридж <br> Осмос мембранасы <br> Ультракүлгін сүзгі",
            home58: "2-кезең<br> Пастерлеу",
            home59: "Бұл кезеңде сүзгілерден өткен табиғи су қажетті компоненттермен, хош иістермен және табиғи шырындармен байытылып, 93-95 градусқа дейін қайнатылады.",
            home60: "3-кезең: Қаптама",
            home61: "Дайын өнім қайнаған кезде сыйымдылығы 0,5 және 1 литр пластикалық ыдыстарға құйылады.",

            home62: "СЕРГІСТІК",
            home621: "Micco табиғи ингредиенттері сізге қуат пен балғындық береді. Әр күнді энергиямен бастаңыз.",
            home63: "ТАБИҒИ",
            home64: "Micco тек табиғи жемістерден жасалған. Денеңізді таза ингредиенттерден жасалған және жасанды қоспасыз сусынмен қорғаңыз.",
            home65: "ДӘМДІ",
            home66: "Micco-ның әрбір жұтымы ерекше дәмімен сізге жағымды рахат сыйлайды. Оның таза дәмінен ләззат алыңыз.",
            home67: "КҮМІС ТҮРІ",
            home68: "Micco сізге әр уақытта басқа дәм беру үшін әртүрлі жеміс дәмін ұсынады. Сүйіктіңізді таңдап, ләззат алыңыз.",

            home69: "Біздің клиенттер не дейді",
            home70: "Ескертпелер",
            home71: "Мен Micco-ны алғаш рет қолданып көргенімде, оның табиғи дәмі мен жағымды сергітетін қасиеттері маған қатты ұнады. Енді мен оны күнде ішемін!",
            home72: "Еркінова Солиха",
            home73: "Micco сусыны маған қуат пен сергектік береді. Ол жұмыс күні бойы қолдау көрсету үшін әрқашан менімен бірге. Оның табиғи дәмі өте жағымды!",
            home74: "Акбаров Жасур",
            home75: "Мен салауатты өмір салтын ұстанамын, сондықтан мен тек табиғи сусындарды ішемін. Мен Micco-да жасанды қоспалардың жоқтығына өте қуаныштымын!",
            home76: "Юлдошева Малика",

            home77: "Байланыс",
            home78: "бізбен хабарласыңы",
            home79: "Ынтымақтастық үшін",
            home80: "Біздің ынтымақтастығымыздың арқасында жаңа мүмкіндіктер ашылады.",
            home81: "ХАБАРЛАМА ЖІБЕРУ",
            
            home82: "Байланыс",
            home83: "Тел..",
            home84: "Email..",
            home85: "Мекен-жайы: Ташкент қаласы, Янги Хаёт ауданы, Юлдош ауданы-10, 63-А",
            home86: "кафедралар",
            home87: "біз туралы",
            home88: "Біздің өнімдер",
            home89: "Клиенттер",
            home90: "Байланыс",
            home91: "Mikko өнімдері",
            home92: "мико гранаты",
            home93: "micco-Алма",
            home94: "Микко-Киви",
            home95: "Мико-манго",
            home96: "Барлық құқықтар қорғалған. Дизайн және өндіріс",

            adash1: "Мәліметтер",
            adash2: "Енгізіңіз",
            adash3: "Енгізіңіз",
            adash4: "сіздің атыңыз",
            adash5: "өз пікіріңізді жазыңыз...",
        }
    };

    let currentLang = localStorage.getItem("lang") || "uz";
    setLanguage(currentLang);

    // **Til menyusini ochish va yopish (mobil versiya uchun)**
    langBtn.addEventListener("click", function (e) {
        e.stopPropagation();
        langDropdown.classList.toggle("show-dropdown");
    });

    // **Tilni tanlash**
    langOptions.forEach(option => {
        option.addEventListener("click", function (e) {
            e.preventDefault();
            setLanguage(option.dataset.lang);
            langDropdown.classList.remove("show-dropdown");
        });
    });

    // **Foydalanuvchi boshqa joyga bossin, menyu yopiladi**
    document.addEventListener("click", function (e) {
        if (!langDropdown.contains(e.target) && !langBtn.contains(e.target)) {
            langDropdown.classList.remove("show-dropdown");
        }
    });

    function setLanguage(lang) {
        if (!translations[lang]) return;

        Object.keys(translations[lang]).forEach(id => {
            let el = document.getElementById(id);
            if (el) {
                el.innerHTML = translations[lang][id]; // ✅ `innerHTML` ishlatilmoqda
            } else {
                console.warn(`Element topilmadi: #${id}`);
            }
        });

        localStorage.setItem("lang", lang);

        // **Tanlangan tilni tugmachada aks ettirish**
        const selectedLang = document.querySelector(`.lang-dropdown a[data-lang="${lang}"]`);
        if (selectedLang) {
            const selectedFlag = selectedLang.querySelector("img").src;
            const selectedText = selectedLang.textContent.trim();
            langBtn.innerHTML = `<img src="${selectedFlag}" class="flag-icon"> ${selectedText}`;
        }
    }
});
